### ISSUE TITLE
In custom LayoutManager (extends RecyclerView.LayoutManager) RecyclerView.getChildViewHolderInt NullPointerException issue

### ISSUE THREAD

**Issue by chijikpijik** [devunwired/recyclerview-playground#5]
Hi! 
After trying similar to this (simplify version):

```
@Override
public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {
     ....
     addView(new TextView(mRecyclerView.getContext()))
}
```

I have an exception:

```
java.lang.NullPointerException
    at android.support.v7.widget.RecyclerView.getChildViewHolderInt(RecyclerView.java:2497)
    at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:4807)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:4803)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:4791)
```

I can't add to RecyclerView child view without ViewHolder?

**Comment by byvlstr** [comment]
Hi,
I am facing the same problem, but I obtained the view from the adapter, like this:
`for (int i = 0; i < getItemCount(); i++){
                View newBadge = recycler.getViewForPosition(i);
            }`
Thanks for your help!

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.isRemoved()' on a null object reference
